# Generated by Django 4.0.3 on 2022-04-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple_iphone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IphoneFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
