# Generated by Django 4.0.4 on 2022-04-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple_iphone', '0002_iphonefeatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='iphonefeatures',
            name='image',
            field=models.ImageField(default=1, upload_to='pics'),
            preserve_default=False,
        ),
    ]
