# Generated by Django 4.0.3 on 2022-04-21 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apple_iphone', '0003_iphonefeatures_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iphonemodels',
            name='short_information',
        ),
        migrations.RemoveField(
            model_name='iphonemodels',
            name='summary_description',
        ),
        migrations.RemoveField(
            model_name='iphonemodels',
            name='summary_name',
        ),
    ]
